Modal Component 구현
second-hand-team-04/second-hand-max-fe pull request #7
Opened 2023-08-24 07:31 UTC by bakhacode

## Issues

- #3

## What is this PR? 👓
  -  라이트한 모달 틀에 각각 다른 스타일과 로직을 가진 두 개의 모달을 주입해서 구현
## Key changes 🔑

## To reviewers 👋
최대한 해본다고 해봤는데 방향이 맞는지는 의문이네요 😂 최대한 카카모토비 코드 참고해가면서 해봤는데 잘못된 부분 있으면 정말 편하게 다 피드백 주셔도 됩니다!

2023-08-24 13:13 UTC, Kakamotobi requested changes

2023-08-24 13:13 UTC, Kakamotobi commented on src/styles/modal/ModalStyles.ts
이 파일은 `components/common/Modal/` 안으로 옮기는게 더 좋을것 같습니다

2023-08-24 13:13 UTC, Kakamotobi commented on src/components/common/Modal/CategoryModal.tsx
> +import x from "@assets/icon/x.svg";
`x`보다 `xIcon` 또는 `closeIcon`등이 더 명확할거 같습니다

2023-08-24 13:13 UTC, Kakamotobi commented on src/components/common/Modal/CategoryItem.tsx
> +      {/* <img width="40px" height="40px" src={item.imageUrl} alt={item.title} /> */}
확인 다 하셨으면 주석 지워도 될것 같습니다

2023-08-24 13:13 UTC, Kakamotobi commented on src/components/common/Modal/CategoryModal.tsx
> +  const [selectedCategory, setSelectedCategory] = useState(1);
`selectedCategoryId`로 이름을 바꾸면 이해하기 더 쉬울것 같습니다

2023-08-24 13:13 UTC, Kakamotobi commented on src/components/common/Modal/CategoryModal.tsx
> +];
Mock data는 msw로 옮기는게 좋을것 같아요 👍

2023-08-24 13:13 UTC, Kakamotobi commented on src/components/common/Modal/Modal.tsx
> +}
- 모달 구조를 아래처럼하는건 어떨까요?
- 그리고 모달 컴포넌트에서 backdrop(dim)을 적용해주면 좋을거 같아요.
  - i.e. `Modal`은 단순히 `children`을 backdrop앞에 그려주는 컴포넌트.

```tsx
export default function Modal({
  isOpen,
  onClose, // Modal 밖(backdrop)을 클릭스시 닫기 위함.
  children,
}: {
  isOpen: boolean;
  onClose: () => void;
  children: ReactNode;
}) {
  return (
    <StyledModal onClick={onClose}> // Backdrop 적용
      <div>{children}</div> // 모달 박스
    </StyledModal>
  );
}
```
```tsx
// Example 1
<div>
  <Modal isOpen={isRegionModalOpen} onClose={onRegionModalClose}>
    <header>
      <h3>제목</h3>
      <button onClick={onRegionModalClose}>
        <img src={xIcon} alt="동네 설정 모달 닫기" />
      </button>
    </header>
  </Modal>
</div>

// Example 2
<div>
  <Modal isOpen={isRegionModalOpen} onClose={onRegionModalClose}>
    <header>
      <button onClick={onGoBack}>
        <img src={chevronLeft} alt="뒤로 가기" />
      </button>
    </header>
  </Modal>
</div>
```

2023-08-24 13:16 UTC, Kakamotobi commented
그리고 `components/common/Modal`안에는 정말 `Modal` 범용 컴포넌트 모듈만 들어있는게 좋을거 같아요. `Modal` 컴포넌트를 사용해서 만든 다른 컴포넌트 (Ex: `CategoryModal`)은 따로 빼는게 좋을 것 같습니다 👍

2023-08-24 14:04 UTC, Kakamotobi commented on src/components/common/Modal/CategoryModal.tsx
> +];
제가 MSW 초기화해서 PR 올렸는데 먼저 merge하고 받으신 후에 옮기면 될것 같습니다

2023-08-24 15:17 UTC, bakhacode commented on src/styles/modal/ModalStyles.ts
고민하다가 스타일로 뺐는데 한 쪽으로 모으는 게 맞군요 수정했습니다!

2023-08-24 15:19 UTC, bakhacode commented on src/components/common/Modal/CategoryModal.tsx
> +];
넵 Region에 있는 Mock Data도 동일하게 처리하겠습니다!

2023-08-24 16:23 UTC, bakhacode commented on src/components/common/Modal/Modal.tsx
> +}
카카모토비가 제안해주신 방식으로 구조 수정하고 RegionModal 같은 경우 첫 메인 화면과 동네 추가시 화면이 달라져서 분리해봤어요! 나머지 피드백 주신 부분들도 전부 수정완료했습니다 확인하고 수정해야하는 부분 있으면 코멘트 달아주세요! 👍

2023-08-25 01:23 UTC, Kakamotobi commented on src/components/Category/CategoryModal.tsx
> +  };
이거는 props로 받아도 될거 같아요

2023-08-25 01:28 UTC, Kakamotobi commented on src/components/Region/RegionModalAdd.tsx
> +export default function RegionModalAdd({
`RegionAddModal`이 더 명확할것 같습니다

2023-08-25 01:29 UTC, Kakamotobi commented on src/components/Region/RegionModalMain.tsx
> +export default function RegionModalMain({
`RegionSelectModal`이 좋을것 같습니다

2023-08-25 01:31 UTC, Kakamotobi commented on src/components/Region/RegionModal.tsx
> +  const [isAddMode, setIsAddMode] = useState(false);
`isRegionAddModal`이 그나마 좀 더 이해하기 쉬울 것 같아요

2023-08-25 01:34 UTC, Kakamotobi commented on src/components/Region/RegionModalAdd.tsx
> +  onRegionBack: () => void;
`onRegionBack` 이름만 봐서는 헷갈리는거 같아요. 🫨

2023-08-25 01:42 UTC, Kakamotobi commented on src/components/Region/RegionModalMain.tsx
> +  const canPerformAction = selectedRegionList.length !== 1;
읽기 쉽게 아래처럼 해봐도 될것 같습니다.
삭제: 2개일 때만 가능
추가: 1개일 때만 가능

```ts
const selectedOneRegion = selectedRegionList.length === 1
const selectedTwoRegions = selectedRegionList.length === 2
```

2023-08-25 01:44 UTC, Kakamotobi approved these changes

2023-08-25 01:45 UTC, merged